FROM registry.access.redhat.com/ubi8/python-311:1

LABEL name="fids-api" \
      summary="Nice Côte d'Azur FIDS API" \
      io.openshift.expose-services="8080:http"

WORKDIR /opt/app-root/src
COPY --chown=1001:0 requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt
COPY --chown=1001:0 app.py .

EXPOSE 8080
CMD ["python", "-u", "app.py"]
