FROM registry.access.redhat.com/ubi8/httpd-24:1

LABEL name="fids-web" \
      summary="Nice Côte d'Azur Terminal 2 departure board" \
      io.openshift.expose-services="8080:http"

COPY --chown=1001:0 entrypoint.sh /usr/local/bin/fids-entrypoint
COPY --chown=1001:0 index.html /usr/share/fids/index.html
COPY --chown=1001:0 index.html /var/www/html/index.html

USER root
COPY fids-proxy.conf /etc/httpd/conf.d/fids-proxy.conf
RUN sed -i 's/\r$//' /usr/local/bin/fids-entrypoint /etc/httpd/conf.d/fids-proxy.conf \
 && chmod 0755 /usr/local/bin/fids-entrypoint \
 && chmod -R a+rwX /var/www/html /usr/share/fids
USER 1001

ENTRYPOINT ["/usr/local/bin/fids-entrypoint"]
CMD ["/usr/bin/run-httpd"]

EXPOSE 8080
